name: Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'yarn'
          
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --verbose
          yarn rebuild-native --verbose
        
      - name: Build
        run: |
          echo "Starting TypeScript build..."
          yarn build:ts --verbose
          echo "Starting renderer build..."
          yarn build:renderer --verbose
          echo "Copying assets..."
          yarn copy-assets --verbose
          echo "Running verification..."
          yarn verify --verbose
        env:
          NODE_ENV: production
          DEBUG: electron-builder
        
      - name: Build Windows
        run: yarn electron-builder --win --x64 --debug
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          DEBUG: electron-builder
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            build/*.exe
            yarn-error.log
            
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'yarn'
          
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --verbose
          yarn rebuild-native --verbose
        
      - name: Build
        run: |
          echo "Starting TypeScript build..."
          yarn build:ts --verbose
          echo "Starting renderer build..."
          yarn build:renderer --verbose
          echo "Copying assets..."
          yarn copy-assets --verbose
          echo "Running verification..."
          yarn verify --verbose
        env:
          NODE_ENV: production
          DEBUG: electron-builder
        
      - name: Build Mac
        run: yarn electron-builder --mac --debug
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          DEBUG: electron-builder
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: |
            build/*.dmg
            yarn-error.log